In [46]:
import numpy as np
import pandas as pd

# 读入整理后的数据

In [47]:
data = pd.read_csv('jinan+.csv')
data.head()

档位  本期政策  需求满足率   订购率    订足面  订足率（中烟） 订足率(济南) 户均条数  下期政策     价位  是否省内
0  30     8  1.00   0.67  1.00       0.0   1.00     8     8  583.0     0
1  29     8  0.84   0.63  0.73       0.0   0.87   6.7     8  583.0     0
2  28     8  0.95   0.38  0.55       0.0   0.74   5.8     8  583.0     0
3  27     7  0.91   0.28  0.55       0.0   0.77     5     7  583.0     0
4  26     7  0.95   0.21  0.47       0.0   0.73   4.5     7  583.0     0

In [48]:
data1 = data.copy()

删去带‘-’的无效数据，目前认为对这些档位不做调整

In [49]:
data_clean = data1.replace('-', 0, inplace=False)


In [50]:
data_clean['政策变动'] = data_clean['下期政策'] - data_clean['本期政策']

In [51]:
data_clean.head()

档位  本期政策  需求满足率   订购率    订足面  订足率（中烟） 订足率(济南) 户均条数  下期政策     价位  是否省内  政策变动
0  30     8  1.00   0.67  1.00       0.0   1.00     8     8  583.0     0     0
1  29     8  0.84   0.63  0.73       0.0   0.87   6.7     8  583.0     0     0
2  28     8  0.95   0.38  0.55       0.0   0.74   5.8     8  583.0     0     0
3  27     7  0.91   0.28  0.55       0.0   0.77     5     7  583.0     0     0
4  26     7  0.95   0.21  0.47       0.0   0.73   4.5     7  583.0     0     0

构建机器学习模型，自变量为'档位','需求满足率','订购率','订足面','订足率(济南)','户均条数','价位'，因变量为'政策变动'

In [52]:
df = data_clean[['本期政策','档位','需求满足率','订购率','订足面','订足率（中烟）','订足率(济南)','户均条数','价位','是否省内','政策变动']]
df.head()

本期政策  档位  需求满足率   订购率    订足面  订足率（中烟） 订足率(济南) 户均条数     价位  是否省内  政策变动
0     8  30  1.00   0.67  1.00       0.0   1.00     8  583.0     0     0
1     8  29  0.84   0.63  0.73       0.0   0.87   6.7  583.0     0     0
2     8  28  0.95   0.38  0.55       0.0   0.74   5.8  583.0     0     0
3     7  27  0.91   0.28  0.55       0.0   0.77     5  583.0     0     0
4     7  26  0.95   0.21  0.47       0.0   0.73   4.5  583.0     0     0

# 数据分析模块（决策树）

In [53]:
df.shape

(1500, 11)

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer #特征转换器
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn import tree

In [55]:
X = df[['本期政策','档位','需求满足率','订购率','订足面','订足率（中烟）','订足率(济南)','户均条数','价位','是否省内']]
y = df['政策变动']

In [61]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=2)  # 将数据进行分割

In [62]:
# vec = DictVectorizer(sparse=False)
# X_train = vec.fit_transform(X_train.to_dict(orient='record'))   #对训练数据的特征进行提取
# X_test = vec.transform(X_test.to_dict(orient='record'))         #对测试数据的特征进行提取

In [63]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train,y_train)
y_predict = dtc.predict(X_test)

In [64]:
print('Accracy:',dtc.score(X_test,y_test))
print(classification_report(y_predict,y_test))

Accracy: 0.9333333333333333
              precision    recall  f1-score   support

          -3       0.50      1.00      0.67         1
          -2       0.92      0.79      0.85        14
          -1       0.68      0.71      0.69        24
           0       0.97      0.97      0.97       279
           1       0.87      0.90      0.88        29
           2       0.91      0.91      0.91        22
           3       1.00      0.80      0.89         5
           4       1.00      1.00      1.00         1

    accuracy                           0.93       375
   macro avg       0.86      0.88      0.86       375
weighted avg       0.94      0.93      0.93       375



In [65]:
y_predict

array([ 1, -1,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,
       -1, -2,  0,  0,  3,  0, -1,  0,  0,  2,  2,  0,  0,  0,  0,  0,  0,
        0,  0,  2,  0, -1, -1,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,
        0, -2, -2,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  2,  0,  2,  0,  0,  3,  0,  0,  0,  0,  0,  1,  0,  1,  0,
        0,  0, -1,  2,  0, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0, -1,  0,  0,  0,  2,  0,  0,  0, -1,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0, -2,  3,  0,  0,  0,  0,  1,  0,  0,  0,  1, -2,
        0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,
       -2,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1,  0,  1,  0,  0,
        0,  0,  2,  0,  0, -2,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,
        0,  1,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [66]:
y_test.values

array([ 1, -1,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,
        0, -2,  0,  0,  3,  0, -1,  0,  0,  2,  2,  0,  0,  0,  0,  0,  0,
        0,  0,  2,  0, -1,  0,  0,  0,  0, -1,  0,  2,  1,  0,  0,  0,  0,
        0, -2, -2,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  2,  0,  2,  0,  0,  3,  0,  0,  0,  0,  0,  1,  0,  1,  0,
        0,  0, -1,  2,  0, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  2,  0,  0,  0, -1,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  1, -2,
        0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0, -1,
       -2,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1,  0,  1,  0,  0,
        0,  0,  2,  0,  0, -2,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,
        0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [67]:
dtc.feature_importances_

array([0.13336519, 0.14614935, 0.03426115, 0.11155735, 0.0563304 ,
       0.08297511, 0.06076791, 0.04355559, 0.3183051 , 0.01273285])

In [18]:
with open("jcs2.dot", 'w') as f:
    f = tree.export_graphviz(dtc, out_file = f)